name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: dyrean/crwn-clothing@main
        with:
          excluded_paths: "ignore,.github"
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.7.0
        with:
          excluded_paths: "ignore,.github"
          branch: "main"